<?php

/**
 * @file
 * user picture field
 */

/**
 * Implements hook_menu().
 */
function user_picture_field_menu() {
  $items['admin/config/people/user_picture_field'] = array(
    'title' => 'User picture field',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('user_picture_field_config_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'user_picture_field.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_config_info().
 */
function user_picture_field_config_info() {
  $prefixes['user_picture_field.settings'] = array(
    'label' => t('User picture field settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_user_insert().
 */
function user_picture_field_user_insert($account) {
  $config = config('user_picture_field.settings');
  $source_field = $config->get('source_field');
  $source_entity = $config->get('source_entity');
  $fid = 0;
  if ($source_entity == 'user') {
    if (isset($account->{$source_field})) {
      foreach ($account->{$source_field} as $langcode => $items) {
        if (isset($items[0]['fid'])) {
          $fid = $items[0]['fid'];
          break;
        }
        else {
          $field_info = field_info_field($source_field);
          if (!empty($field_info['settings']['default_image'])) {
            $fid = $field_info['settings']['default_image'];
            break;
          }
        }

      }
    }
  }
  elseif ($source_entity == 'profile') {
    $source_bundle = $config->get('source_bundle');
    $profile = profile_load_by_user($account, $source_bundle);
    if (empty($profile)) {
      return;
    }
    if (isset($profile->{$source_field})) {
      foreach ($profile->{$source_field} as $langcode => $items) {
        if (isset($items[0]['fid'])) {
          $fid = $items[0]['fid'];
          break;
        }
        else {
          $field_info = field_info_field($source_field);
          if (!empty($field_info['settings']['default_image'])) {
            $fid = $field_info['settings']['default_image'];
            break;
          }
        }

      }
    }

  }
  if ($fid) {
    db_update('users')
      ->fields(array('picture' => $fid))
      ->condition('uid', $account->uid)
      ->execute();
  }
  //user_save($account);
}

/**
 * Implements hook_user_update().
 */
function user_picture_field_user_update($account) {
  user_picture_field_user_insert($account);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function user_picture_field_form_user_profile_form_alter(&$form, &$form_state) {
  //remove existing user picture fieldset.
  if (isset($form['picture'])) {
    unset($form['picture']);
  }
}

/**
 * Implements hook_profile_insert().
 */
function user_picture_field_profile_insert($profile) {
  $config = config('user_picture_field.settings');
  $source_entity = $config->get('source_entity');
  $source_bundle = $config->get('source_bundle');
  if ($source_entity == 'profile' && $source_bundle == $profile->type) {
    $fid = 0;
    $source_field = $config->get('source_field');
    if (isset($profile->{$source_field})) {
      foreach ($profile->{$source_field} as $langcode => $items) {
        if (isset($items[0]['fid'])) {
          $fid = $items[0]['fid'];
          break;
        }
        else {
          $field_info = field_info_field($source_field);
          if (!empty($field_info['settings']['default_image'])) {
            $fid = $field_info['settings']['default_image'];
            break;
          }
        }
      }
    }
    if ($fid) {
      db_update('users')
        ->fields(array('picture' => $fid))
        ->condition('uid', $profile->uid)
        ->execute();
    }
  }

}

/**
 * Implements user_picture_field_profile_update().
 */
function user_picture_field_profile_update($profile) {
  user_picture_field_profile_insert($profile);
}
